# SPDX-License-Identifier: GPL-2.0-only
# Copyright (C) 2024 Intel Corporation

obj-$(CONFIG_LIBETH)		+= libeth.o

libeth-objs			+= rx.o
libeth-objs			+= libeth_controlq.o
libeth-objs			+= libeth_virtchnl.o
libeth-objs			+= libeth_dev.o
libeth-objs			+= libeth_mem.o
libeth-objs			+= libeth_idc.o
