# SPDX-License-Identifier: GPL-2.0-only
# Copyright (C) 2024 Intel Corporation

# Makefile for Intel(R) Infrastructure Data Path Function Linux Driver

obj-$(CONFIG_IDPF) += idpf.o

idpf-y := \
	idpf_controlq.o		\
	idpf_controlq_setup.o	\
	idpf_dev.o		\
	idpf_ethtool.o		\
	idpf_fltr.o		\
	idpf_lib.o		\
	idpf_main.o		\
	idpf_netdev.o		\
	idpf_singleq_txrx.o	\
	idpf_txrx.o		\
	idpf_vf_dev.o		\
	idpf_virtchnl.o 	\
	idpf_vport.o		\
	idpf_vport_config.o	\
	idpf_vport_q.o
